//GLOBAL CONSTANTS

//CLIENT 
var CLIENTS=new Array(
	/*GPS*/
	CLIENT_AAP,
	CLIENT_ABBVIE,
	CLIENT_ADP,
	CLIENT_ADVANCE_AUTO_PARTS,
	CLIENT_AIRBUS,
	CLIENT_AGC_GLASS,
	CLIENT_AMERICAN_AIRLINES,
	CLIENT_ANGLO_AMERICAN,
	CLIENT_ANIMAS,
	CLIENT_APPLIED_MATERIALS,
	CLIENT_APPLIED_MATERIAL_PROCUREMENT,
	CLIENT_APMM,
	CLIENT_ARC_INTERNATIONAL,
	CLIENT_ATT,
	CLIENT_AVON,
	CLIENT_AXA,
	CLIENT_AXA_NA,
	//CLIENT_BBC, 
	CLIENT_BLUESCOPESTEEL,
	CLIENT_BMW,
	CLIENT_BD, 
	CLIENT_CASCADES,
	CLIENT_CEMEX,
	CLIENT_CELESTICA,
	CLIENT_CIBC,
	CLIENT_COCA_COLA_GLOBAL,
	CLIENT_CONVATEC,
	CLIENT_CORNING,
	CLIENT_CROSSMARK,
	CLIENT_DOW,
	CLIENT_DIGITAL_ENGAGEMENT,
	CLIENT_DIXONS_CARPHONE,
	//CLIENT_DOW_NEW,
	CLIENT_DOW_MANILA,					  
	CLIENT_F_AND_A,
	CLIENT_FEDERAL_MOGUL,
	CLIENT_FERGUSON,
	CLIENT_FREDDIE_MAC,
	CLIENT_GENESIS,
	CLIENT_GOOGLE,
	CLIENT_GOODYEAR,
	CLIENT_GPS2016,
	CLIENT_HITACHI,
	CLIENT_HONDA,
	CLIENT_HONDA_HR_ASIA,
	CLIENT_HOMEDEPOT,
	CLIENT_IBM,
	CLIENT_IBM_FA_PROCURE,
	CLIENT_ING,
	CLIENT_ITG,
	CLIENT_ITRON,
	CLIENT_JARDEN,
	CLIENT_JDE,
	CLIENT_JOHNSON_JOHNSON,
	CLIENT_KENNAMETAL,
	CLIENT_LINDE, 
	CLIENT_LUFTHANSA,
	CLIENT_MANPOWER,
	CLIENT_MARATHON_OIL,
	CLIENT_MEAD_JOHNSON,
	CLIENT_MONDELEZ,
	CLIENT_NESTLE,
	CLIENT_NEWELL_RUBBERMAID,
	CLIENT_ORIFLAME,
	CLIENT_PANASONIC,
	CLIENT_PEARSON,
	CLIENT_PEPSICO, 
	CLIENT_PREMIER_FARNELL, 
	CLIENT_PFIZER,
	CLIENT_RENAULT,
	CLIENT_RIOTINTO, 
	CLIENT_ROLLS_ROYCE, 
	CLIENT_ROYAL_FRIESLAND_CAMPINA,
	CLIENT_RPO2016,
	CLIENT_SANTANDER, 
	CLIENT_SIBCO,
	CLIENT_SINGAPORE_AIRLINES,
	CLIENT_SOK,
	CLIENT_SPX,
	CLIENT_TAKEOFF,
	CLIENT_TELSTRA,
	CLIENT_TELSTRA_PROCURE,
	//CLIENT_TELSTRA_RFI,
	CLIENT_TD_BANK, 
	CLIENT_TOSHIBA,
	CLIENT_TYCO, 
	CLIENT_UNILEVER, 
	CLIENT_UTC_CARRIER,
	CLIENT_VODAFONE,	
	
	/*ArCollect*/
	CLIENT_ARCOLLECT_DEV,
	
	/*GBS*/
	CLIENT_GBS,
	CLIENT_ESI,
	CLIENT_PG,
	CLIENT_VERIZON,
	CLIENT_TWITTER,
	CLIENT_VANTAGE,
	CLIENT_ANZ,
	CLIENT_SUNTORY,
	CLIENT_WILLIAMS,
	CLIENT_AETNA,
	CLIENT_OPTUS,
	CLIENT_TONEN_GENERAL_FA,
	CLIENT_TONEN_GENERAL_HR,
	CLIENT_TITAN_AMERICA,
	CLIENT_UNILEVER_GLOBAL,
	CLIENT_WHIRLPOOL,
	CLIENT_YAMATO,
	
	/*Special Cardview*/
	CLIENT_ANALYSTS,
	CLIENT_BANKING,
	CLIENT_COLABS,
	CLIENT_ISPM,
	CLIENT_LEARNING,
	CLIENT_VANTAGE_GPS,
	CLIENT_VANTAGE_DEMO
);

//SETS THE CURRENT CLIENT
var CURRENT_CLIENT=CLIENT_VANTAGE_DEMO;


//FREEZES ALL ANIMATIONS/TRANSITIONS ON SITE (VIDEOBOX, SPLASH and IMAGEBOX)
//OVERRIDES OTHER VARIABLES BELOW
var NO_ANIMATIONS = 0;

//FREEZES ONLY ANIMATIONS/TRANSITIONS ON SPLASH PAGE
var NO_SPLASH_ANIMATIONS = 0;

//FREEZES ONLY ANIMATIONS/TRANSITIONS ON VIDEOBOX
//var NO_VIDEOBOX_ANIMATIONS=0; //not yet implemented

//ONLINE_VIDEOS=0	->	videos from mp4 (local) files
//ONLINE_VIDEOS=1	->	videos from intranet (media hub)
//ONLINE_VIDEOS=2	->	videos from internet (youtube) + mp4 (local)
var ONLINE_VIDEOS = 2;

//enable authentication
var AUTHENTICATION = 0;

// Host URL
var HOST="http://9.3.68.213:3000"; //http://9.3.68.213:3000";// http://localhost:3000


///show db comment icons
var DBD_COMMENTS = 1;

//Dashboard Client Name
var DBD_CLIENT_NAME="procter%26gamble";

//client default geo location
var DBD_CLIENT_DEFAULT_GEO="Europe";

//Default Country for dashboard
var DBD_DEFAULT_COUNTRY="China";

/****END DASHBOARD CONSTANT VARIABLES**/
//DEFAULT VALUES

//enable apps chapter
var HAS_APPS_CHAPTER = 0;

//enable RPO chapter
var HAS_RPO_CHAPTER = 0;

//nestle orals link
var HAS_ORALS = 0;

//enable generic chapters
var HAS_GENERIC_CHAPTERS = 1;

//changes the navigation structure to a client-focused structure (example: Santander)
var CLIENT_STRUCTURE = 0;

//To enable the js alert for testing
var ALERT = 0;

//client config overrides default
var config_options = Array('HAS_APPS_CHAPTER','HAS_ORALS', 'HAS_RPO_CHAPTER', 'HAS_GENERIC_CHAPTERS', 'CLIENT_STRUCTURE', 'NO_ANIMATIONS', 'NO_SPLASH_ANIMATIONS');
for (co in config_options) {
	if (CURRENT_CLIENT) {
		if (CURRENT_CLIENT.hasOwnProperty(config_options[co])) {
			eval(config_options[co] + '=CURRENT_CLIENT.' + config_options[co]);
		}
	}
}
